name: CodeTEI CI

on:
  push:
    paths: [ '**.xml', 'schema/**', '.github/workflows/ci.yml' ]
  pull_request:
    paths: [ '**.xml', 'schema/**' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build schemas
        run: bash tools/build-schema.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: schemas
          path: schema/build/CodeTEI-*
      - name: Commit & push on main (only if tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add built schemas for ${{ github.ref_name }}"
          file_pattern: schema/build/*
