name: CodeTEI CI

on:
  push:
    paths: [ '**.xml', 'schema/**', '.github/workflows/ci.yml' ]
  pull_request:
    paths: [ '**.xml', 'schema/**' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Jing
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jing
      - name: Validate XML files
        run: bash ./tools/validate.sh
